import bpy,json,ast,hashlib
from pathlib import Path
r=Path.cwd();out=r/'docs/image/modeling-tests/ninola-01M/2026-10-08-pass-v001/refined-v002';rec=json.loads((out/'build_record.json').read_text());mask=json.loads((out/'edit_mask.json').read_text());moved=set(mask['moved_vertices']);protected=set(mask['protected_vertices']);sha_bytes=lambda b:hashlib.sha256(b).hexdigest();tree=ast.parse((r/'docs/image/modeling-tests/ninola-01L/2026-10-08-pass-v003/build_01L3_refined.py').read_text());exec(compile(ast.Module(body=[n for n in tree.body if isinstance(n,ast.FunctionDef) and n.name=='locked_signature'],type_ignores=[]),'sig','exec'))
def read(path,name):
 bpy.ops.wm.open_mainfile(filepath=str(r/path));o=bpy.data.objects[name];bpy.context.view_layer.update();ev=o.evaluated_get(bpy.context.evaluated_depsgraph_get());return {'rest':[list(v.co) for v in o.data.vertices],'world':[list(o.matrix_world@v.co) for v in ev.data.vertices],'faces':[(list(f.vertices),f.material_index) for f in o.data.polygons],'weights':[{o.vertex_groups[g.group].name:g.weight for g in v.groups} for v in o.data.vertices],'materials':[m.name if m else None for m in o.data.materials],'locked':locked_signature(),'matrix':[list(row) for row in o.matrix_world]}
a=read(rec['base_path'],'01L3_Three_Toe_Volume_Reconstruction');b=read(rec['output_path'],rec['object']);n=len(a['rest']);v={'reopen_Rig_Trex_keys_pose_exact':a['locked']==b['locked'],'topology_material_assignments_exact':a['faces']==b['faces'] and a['materials']==b['materials'],'all_weights_exact':a['weights']==b['weights'],'object_matrix_exact':a['matrix']==b['matrix'],'outside_mask_rest_exact':all(a['rest'][i]==b['rest'][i] for i in range(n) if i not in moved),'protected_rest_exact':all(a['rest'][i]==b['rest'][i] for i in protected),'outside_mask_evaluated_world_exact':all(a['world'][i]==b['world'][i] for i in range(n) if i not in moved),'saved_change_count':sum(a['rest'][i]!=b['rest'][i] for i in range(n)),'saved_changed_vertices_match_mask':{i for i in range(n) if a['rest'][i]!=b['rest'][i]}==moved}
for k,x in v.items():
 if isinstance(x,bool):assert x,k
idx=json.loads((r/'docs/image/modeling-tests/ninola-workflow/asset-index.json').read_text());v['source_hashes_unchanged']={k:hashlib.sha256((r/d['local_path']).read_bytes()).hexdigest()==d['sha256'] for k,d in idx['assets'].items() if d.get('local_path')};assert all(v['source_hashes_unchanged'].values());v['output_sha256_verified']=hashlib.sha256((r/rec['output_path']).read_bytes()).hexdigest()==rec['output_sha256'];assert v['output_sha256_verified'];(out/'verification.json').write_text(json.dumps(v,indent=2));print(json.dumps(v))
