from pathlib import Path
import json,hashlib,html
from PIL import Image,ImageDraw,ImageFont
r=Path.cwd();p=Path(__file__).resolve().parent;refs=r/'docs/image/modeling-tests/ninola-01K8/2026-10-08-v001/references';font=ImageFont.truetype('/System/Library/Fonts/Hiragino Sans GB.ttc',25);small=ImageFont.truetype('/System/Library/Fonts/Hiragino Sans GB.ttc',20)
for name,title in [('head_threequarter','頭顎：幾何轉面与色面'),('full_side','全身：主要量體与色面'),('body_style_close','身體：大折面与分塊')]:
 c=Image.new('RGB',(1600,960),(24,35,45));d=ImageDraw.Draw(c);d.text((25,15),'01R｜'+title+'｜同鏡頭唯讀診斷',font=font,fill='white');d.text((25,65),'灰模：不以底色分塊判形狀',font=font,fill='white');d.text((825,65),'上色：來源材質，沒有改色',font=font,fill='white');c.paste(Image.open(p/'captures'/f'{name}_gray.png').resize((760,760)),(20,110));c.paste(Image.open(p/'captures'/f'{name}_color.png').resize((760,760)),(820,110));d.text((25,900),'Q1 v002核可來源｜Workbench評估網格診斷，不代表最終遊戲光照／shader',font=small,fill='white');c.save(p/f'{name}_gray_color.png')
views=[('full_side','全身側視'),('full_other_side','對側'),('full_front','正面'),('full_rear','背面'),('full_top','頂視'),('full_left_oblique','左3/4'),('full_right_oblique','右3/4'),('dorsal_oblique','背部棘刺主次'),('head_side','頭顎側視'),('head_front','頭顎正面'),('head_threequarter','頭顎3/4'),('head_top','頭顎頂視'),('head_body_context','頭顎／胸體銜接'),('body_style_close','身體近距離')]
ref=p/'references';ref.mkdir(exist_ok=True);im=Image.open(refs/'user_reference_5.png');im.save(ref/'concept_overall.png');im.crop((755,525,1536,1024)).save(ref/'concept_head.png');(p/'reference_provenance.json').write_text(json.dumps({'source':str(refs/'user_reference_5.png'),'source_sha256':hashlib.sha256((refs/'user_reference_5.png').read_bytes()).hexdigest(),'head_crop_pixels':[755,525,1536,1024],'role':'user AI Concept visual target; not anatomy proof'},ensure_ascii=False,indent=2))
items=''.join(f'<section><h2>{html.escape(title)}</h2><img src="captures/{name}.png"></section>' for name,title in views);pairs=''.join(f'<img src="{name}_gray_color.png">' for name in ['full_side','head_threequarter','body_style_close']);(p/'index.html').write_text('<!doctype html><html lang="zh-Hant"><meta charset="utf-8"><title>01R 全身比例與風格審視</title><style>body{background:#18232d;color:#edf0f2;font:18px sans-serif;max-width:1500px;margin:30px auto;padding:20px}img{max-width:100%;height:auto}p{line-height:1.7}section{margin:35px 0}a{color:#79dfd2}</style><h1>01R 全身比例／棘刺裝甲／色面與角面風格｜唯讀</h1><p>Q1 v002已核可，本輪20張完整網格診斷圖，來源未改。<a href="REVIEW.md">整體判斷與下一步提案</a>。</p><p>建議保留目前量體與棘刺主次。最小風格候選是頭顎的主面／色面分組比較，先固定輪廓作示意，避免隨機加面或全頭減面。</p><h2>Concept：未配準姿態，僅比較視覺方向</h2><img src="references/concept_overall.png"><img src="references/concept_head.png"><h2>同鏡頭灰模／上色診斷</h2>'+pairs+items+'</html>');print('R review report and 3 same-camera gray/color pairs complete')
