import bpy,json,hashlib,collections
from pathlib import Path
r=Path.cwd();p=Path(__file__).resolve().parent;src=r/'blender/ninola/working/01M8/2026-10-09-v001/ninola_01M8_cranial_identity.blend';before=hashlib.sha256(src.read_bytes()).hexdigest();bpy.ops.wm.open_mainfile(filepath=str(src));o=bpy.data.objects['01M8_Cranial_Identity'];bpy.context.view_layer.update();e=o.evaluated_get(bpy.context.evaluated_depsgraph_get());c=[o.matrix_world@v.co for v in e.data.vertices];weights=[{o.vertex_groups[g.group].name:g.weight for g in v.groups} for v in o.data.vertices];names=[m.name for m in o.data.materials];faces=[list(f.vertices) for f in o.data.polygons];materials=[names[f.material_index] for f in o.data.polygons]
key=lambda i:tuple(round(v,5) for v in c[i]);skin={i for f,m in zip(faces,materials) if m in {'d_tan','d_belly'} for i in f if weights[i].get('jaw',0)>.999};prot={i for f,m in zip(faces,materials) if m not in {'d_tan','d_belly'} or any(weights[j].get('jaw',0)<.999 for j in f) for i in f};pk={key(i) for i in prot};active={i for i in skin if key(i) not in pk};lockedskin=skin-active
bins=[]
for lo,hi in [(2,2.15),(2.15,2.35),(2.35,2.6),(2.6,2.85),(2.85,3.1),(3.1,3.4)]:
 pts=[c[i] for i in skin if lo<=c[i].y<hi];bins.append({'y':[lo,hi],'count':len(pts),'bounds_xyz':[[min(v[k] for v in pts),max(v[k] for v in pts)] for k in range(3)]})
(p/'source_geometry.json').write_text(json.dumps({'vertices':[list(v) for v in c],'faces':faces,'face_materials':materials,'skin_candidate':sorted(skin),'outer_unshared_candidate':sorted(active),'protected_coincident_skin':sorted(lockedskin),'jaw_deforming_teeth':[i for f,m in zip(faces,materials) if m in {'d_bone','d_mouth'} and all(weights[j].get('jaw',0)>.999 for j in f) for i in f]}))
(p/'constraint_inspection.json').write_text(json.dumps({'base_sha256':before,'source_unchanged':hashlib.sha256(src.read_bytes()).hexdigest()==before,'skin_candidate_points':len(skin),'unshared_external_candidate_points':len(active),'protected_shared_skin_points':len(lockedskin),'bins':bins,'notes':'Coordinate bounds in original pose, not Concept measurements; mask is candidate only.'},indent=2));print(json.dumps(bins))
