import bpy,json,hashlib
from pathlib import Path
from mathutils import Vector
r=Path.cwd();p=Path(__file__).resolve().parent;out=p/'captures';out.mkdir(exist_ok=True);src=r/'blender/ninola/working/01R1/2026-10-09-v003/ninola_01R1_geometric_head_jaw.blend';sha=hashlib.sha256(src.read_bytes()).hexdigest();bpy.ops.wm.open_mainfile(filepath=str(src));o=bpy.data.objects['01R1_Geometric_Head_Jaw'];rig=bpy.data.objects['TrexRig'];bpy.context.view_layer.update();co=[list(o.matrix_world@v.co) for v in o.evaluated_get(bpy.context.evaluated_depsgraph_get()).data.vertices];faces=[list(f.vertices) for f in o.data.polygons];weights=[{o.vertex_groups[g.group].name:g.weight for g in v.groups} for v in o.data.vertices]
sc=bpy.data.scenes.new('Temporary_01R_Readonly');sc.world=bpy.data.worlds.new('Temporary_01R_BG');sc.world.color=(.075,.085,.1);sc.render.engine='BLENDER_WORKBENCH';sc.render.resolution_x=sc.render.resolution_y=1100;sc.render.resolution_percentage=100;sc.view_settings.view_transform='Standard';sh=sc.display.shading;sh.light='STUDIO';sh.show_shadows=False;sh.show_cavity=True;sh.single_color=(.6,.64,.68);me=bpy.data.meshes.new('Temporary_01R_Display');me.from_pydata(co,[],faces);me.update();ob=bpy.data.objects.new('Temporary_01R_Display',me);sc.collection.objects.link(ob)
for m in o.data.materials:me.materials.append(m)
for f,x in zip(me.polygons,o.data.polygons):f.material_index=x.material_index
cd=bpy.data.cameras.new('Temporary_01R_Camera');cam=bpy.data.objects.new('Temporary_01R_Camera',cd);sc.collection.objects.link(cam);sc.camera=cam
views={'full_side':((1,0,0),(0,-.95,1.7),10.6),'full_other_side':((-1,0,0),(0,-.95,1.7),10.6),'full_front':((0,1,0),(0,0,1.7),4.5),'full_rear':((0,-1,.1),(0,-.8,1.7),4.5),'full_top':((0,0,1),(0,-.95,1.7),10.6),'full_left_oblique':((1,1,.35),(0,-.7,1.7),10.4),'full_right_oblique':((-1,1,.35),(0,-.7,1.7),10.4),'dorsal_oblique':((1,-1,1),(0,-.8,1.8),9.0),'head_side':((1,0,0),(0,2.55,2.1),3.1),'head_front':((0,1,0),(0,2.55,2.1),2.8),'head_threequarter':((1,1,.25),(0,2.55,2.1),3.2),'head_top':((0,0,1),(0,2.55,2.1),3.2),'head_body_context':((1,1,.2),(0,1.0,1.7),5.7),'body_style_close':((1,-1,.25),(0,-.1,1.9),4.6)};settings={}
for view,(direction,center,scale) in views.items():
 d=Vector(direction).normalized();cd.type='ORTHO';cd.ortho_scale=scale;cam.location=Vector(center)+d*20;cam.rotation_euler=(-d).to_track_quat('-Z','Y').to_euler();sc.view_layers[0].update();sh.color_type='SINGLE' if view in ['full_side','full_front','head_side','head_threequarter','body_style_close'] else 'MATERIAL';sc.render.filepath=str(out/f'{view}.png');bpy.ops.render.render(write_still=True,scene=sc.name);settings[view]={'matrix':[list(row) for row in cam.matrix_world],'scale':scale,'resolution':[1100,1100],'camera_type':'ORTHO','complete_prototype':True,'color':sh.color_type}
bones={b.name:{'head_world':list(rig.matrix_world@b.head),'tail_world':list(rig.matrix_world@b.tail),'parent':b.parent.name if b.parent else None} for b in rig.pose.bones if b.name.startswith(('thigh','shin','foot','tail')) or b.name in ['root','spine1','spine2']};assert hashlib.sha256(src.read_bytes()).hexdigest()==sha
(p/'inspection.json').write_text(json.dumps({'source':str(src.relative_to(r)),'sha256':sha,'object':o.name,'bones':bones,'vertices':len(co),'triangles':sum(len(f)-2 for f in faces),'source_unchanged':True,'pose_edited':False,'no_display_face_mask':True},indent=2));(p/'capture_settings.json').write_text(json.dumps(settings,indent=2));(p/'source_geometry.json').write_text(json.dumps({'vertices':co,'faces':faces,'weights':weights,'materials':[o.data.materials[f.material_index].name for f in o.data.polygons]},indent=2));print('01R 14 read-only whole-body/style views complete')
