import bpy,json,hashlib,ast
from pathlib import Path
r=Path.cwd();p=Path(__file__).resolve().parent
sha_bytes=lambda b:hashlib.sha256(b).hexdigest();tree=ast.parse((r/'docs/image/modeling-tests/ninola-01L/2026-10-08-pass-v003/build_01L3_refined.py').read_text());exec(compile(ast.Module(body=[n for n in tree.body if isinstance(n,ast.FunctionDef) and n.name=='locked_signature'],type_ignores=[]),'sig','exec'))
def get(path,name):
 q=r/path;before=hashlib.sha256(q.read_bytes()).hexdigest();bpy.ops.wm.open_mainfile(filepath=str(q));o=bpy.data.objects[name];rig=bpy.data.objects['TrexRig'];bpy.context.view_layer.update()
 return {'sha256':before,'lock':locked_signature(),'coords':[list(v.co) for v in o.data.vertices],'weights':[{o.vertex_groups[x.group].name:x.weight for x in v.groups} for v in o.data.vertices],'faces':[list(f.vertices) for f in o.data.polygons],'materials':[o.data.materials[f.material_index].name for f in o.data.polygons],'keys':o.data.shape_keys is not None,'bones':len(rig.data.bones),'deform_bones':[b.name for b in rig.data.bones if b.use_deform]}
a=get('blender/ninola/working/01M8/2026-10-09-v001/ninola_01M8_cranial_identity.blend','01M8_Cranial_Identity');b=get('blender/ninola/working/01N1/2026-10-09-v002/ninola_01N1_jaw_volume_reconstruction.blend','01N1_Jaw_Volume_Reconstruction');mask=json.loads((p/'refined-v002/edit_mask.json').read_text());assert a['lock']==b['lock'];assert a['coords']==b['coords'][:len(a['coords'])];assert a['weights']==b['weights'][:len(a['weights'])];assert [a['faces'][i] for i in mask['retained_faces']]==b['faces'][:len(mask['retained_faces'])];assert [a['materials'][i] for i in mask['retained_faces']]==b['materials'][:len(mask['retained_faces'])]
ws=b['weights'][len(a['weights']):];assert all(w=={'jaw':1.0} for w in ws)
report={'Rig_Trex_keys_pose_signature_exact':True,'all_M8_original_coords_weights_exact':True,'outside_jaw_faces_materials_exact':True,'retained_face_count':len(mask['retained_faces']),'new_vertices_only_existing_jaw_bone_weight_one':True,'prototype_has_shape_keys':b['keys'],'bones':b['bones'],'M8_sha256':a['sha256'],'N1_sha256':b['sha256'],'production_integration':False};(p/'refined-v002/protection_verification.json').write_text(json.dumps(report,indent=2));print(json.dumps(report))
