import bpy,json,hashlib,ast,struct
from pathlib import Path
r=Path.cwd();p=Path(__file__).resolve().parent;out=p/'refined-v006';rec=json.loads((out/'build_record.json').read_text());mask=json.loads((out/'edit_mask.json').read_text());sha=lambda q:hashlib.sha256(q.read_bytes()).hexdigest();sha_bytes=lambda b:hashlib.sha256(b).hexdigest();tree=ast.parse((r/'docs/image/modeling-tests/ninola-01L/2026-10-08-pass-v003/build_01L3_refined.py').read_text());exec(compile(ast.Module(body=[n for n in tree.body if isinstance(n,ast.FunctionDef) and n.name=='locked_signature'],type_ignores=[]),'sig','exec'))
bpy.ops.wm.open_mainfile(filepath=str(r/rec['base_path']));a=bpy.data.objects['01M1_Lower_Jaw_Mass_Blockout'];lock=locked_signature();coords=[list(v.co) for v in a.data.vertices];weights=[{a.vertex_groups[g.group].name:g.weight for g in v.groups} for v in a.data.vertices];faces=[list(f.vertices) for f in a.data.polygons];materials=[a.data.materials[f.material_index].name for f in a.data.polygons];bpy.context.view_layer.update();world0=[a.matrix_world@v.co for v in a.evaluated_get(bpy.context.evaluated_depsgraph_get()).data.vertices]
bpy.ops.wm.open_mainfile(filepath=str(r/rec['output_path']));ob=bpy.data.objects[rec['object']];bpy.context.view_layer.update();world=[ob.matrix_world@v.co for v in ob.evaluated_get(bpy.context.evaluated_depsgraph_get()).data.vertices];assert locked_signature()==lock;assert [list(v.co) for v in ob.data.vertices[:len(coords)]]==coords;assert [{ob.vertex_groups[g.group].name:g.weight for g in v.groups} for v in ob.data.vertices[:len(coords)]]==weights
mapping=mask['retained_original_face_mapping'];assert [list(f.vertices) for f in ob.data.polygons[:len(mapping)]]==[faces[i] for i in mapping];assert [ob.data.materials[f.material_index].name for f in ob.data.polygons[:len(mapping)]]==[materials[i] for i in mapping];assert max((world[i]-world0[i]).length for i in range(len(coords)))<1e-6
assert all(materials[i] not in ['d_bone','d_claw','d_mouth'] for i in mask['removed_original_faces'])
near=[]
for f in ob.data.polygons[len(mapping):]:
 aa,bb,cc=[world[i] for i in f.vertices]
 if (bb-aa).cross(cc-aa).length_squared<1e-12:near.append(f.index)
assert not near
b=(p/'dynamic-v006/test-project/models/M3_eight_weights.glb').read_bytes();ln=struct.unpack_from('<I',b,12)[0];g=json.loads(b[20:20+ln]);assert len(g['meshes'])==len(g['skins'])==1;assert len(g['skins'][0]['joints'])==45
result={'reopened_Rig_Trex_15_shape_keys_pose_exact':True,'all_original_rest_coords_weights_exact':True,'retained_original_faces_material_identity_exact':True,'protected_teeth_tongue_original_inner_mouth_jaw_body_exact':True,'new_skin_faces_near_degenerate':near,'original_boundary_vertices_preserved':len(mask['preserved_boundary']),'GLB_meshes':1,'GLB_joints':45,'source_hash_matches':sha(r/rec['base_path'])==rec['base_sha256'],'output_hash_matches':sha(r/rec['output_path'])==rec['output_sha256'],'production_acceptance':False};(out/'verification.json').write_text(json.dumps(result,indent=2));print(json.dumps(result))
