from pathlib import Path
import json,html
from PIL import Image,ImageDraw,ImageFont
p=Path(__file__).resolve().parent;s=p.parent/'2026-10-09-review-v001';font=ImageFont.truetype('/System/Library/Fonts/Hiragino Sans GB.ttc',26);small=ImageFont.truetype('/System/Library/Fonts/Hiragino Sans GB.ttc',20)
views=[('tail_side','完整尾側視灰模'),('tail_top','完整尾頂視灰模'),('tail_oblique','尾巴3/4'),('tail_root_close','尾根銜接'),('hip_side','骨盆／後肢側視'),('hip_left_oblique','骨盆／後肢3/4'),('full_body_side','全身側視'),('full_body_top','全身頂視')]
def compare(A,B,dest,title,extra=False):
 c=Image.new('RGB',(1600,940),(24,35,45));d=ImageDraw.Draw(c);d.text((25,15),'01Q.1 v002｜'+title+'｜實際模型',font=font,fill='white');d.text((25,65),'P1 v002｜核可來源',font=font,fill='white');d.text((825,65),'Q1 v002｜尾中段試作，待審',font=font,fill='white');c.paste(A.resize((760,760)),(20,110));c.paste(B.resize((760,760)),(820,110));d.text((25,890),'尾部限定外皮調整｜原棘刺與固定端部保持｜骨盆、上腿、尾長、尾尖與Rig未改',font=small,fill='white');c.save(dest)
for name,title in views:compare(Image.open(s/'captures'/f'{name}.png'),Image.open(p/'captures'/f'{name}.png'),p/f'{name}_comparison.png',title)
compare(Image.open(s/'captures/tail_side.png').crop((200,380,740,665)),Image.open(p/'captures/tail_side.png').crop((200,380,740,665)),p/'tail_mid_close_comparison.png','中段腹線近距離（兩側相同裁切）')
for name,title in [('tail3_yaw_plus12','尾3局部yaw +12°'),('tail3_yaw_minus12','尾3局部yaw -12°'),('tail4_pitch_plus8','尾4局部pitch +8°')]:compare(Image.open(p/'pose-captures'/f'{name}_source.png'),Image.open(p/'pose-captures'/f'{name}_Q1.png'),p/f'{name}_comparison.png',title)
items=''.join(f'<section><h2>{html.escape(title)}</h2><img src="{name}_comparison.png"></section>' for name,title in views);poses=''.join(f'<img src="{name}_comparison.png">' for name in ['tail3_yaw_plus12','tail3_yaw_minus12','tail4_pitch_plus8']);(p/'index.html').write_text('<!doctype html><html lang="zh-Hant"><meta charset="utf-8"><title>01Q.1 尾中段外皮試作</title><style>body{background:#18232d;color:#edf0f2;font:18px sans-serif;max-width:1500px;margin:30px auto;padding:20px}p{line-height:1.7}img{max-width:100%;height:auto}section{margin:35px 0}a{color:#79dfd2}</style><h1>01Q.1 v002 尾中段外皮試作｜待審</h1><p>左核可P1，右Q1獨立試作。有限調整腰段／中段腹線与側寬，原棘刺、固定端部、骨盆上腿、尾長尖及Rig保持。<a href="REPORT.md">點評、檢查與下一步</a>。</p><h2>中段近距離</h2><img src="tail_mid_close_comparison.png">'+items+'<h2>有限人造姿態回放</h2><p>不是完整遊戲動畫／碰撞或全尾變形驗收。</p>'+poses+'</html>');print('8 whole-region comparisons, 1 local crop, 3 pose comparisons complete')
