import bpy,json,hashlib,ast
from pathlib import Path
r=Path.cwd();p=Path(__file__).resolve().parent
sha_bytes=lambda b:hashlib.sha256(b).hexdigest();tree=ast.parse((r/'docs/image/modeling-tests/ninola-01L/2026-10-08-pass-v003/build_01L3_refined.py').read_text());exec(compile(ast.Module(body=[n for n in tree.body if isinstance(n,ast.FunctionDef) and n.name=='locked_signature'],type_ignores=[]),'sig','exec'))
def get(path,name):
 q=r/path;before=hashlib.sha256(q.read_bytes()).hexdigest();bpy.ops.wm.open_mainfile(filepath=str(q));o=bpy.data.objects[name];rig=bpy.data.objects['TrexRig'];bpy.context.view_layer.update()
 return {'sha256':before,'lock':locked_signature(),'coords':[list(v.co) for v in o.data.vertices],'weights':[{o.vertex_groups[x.group].name:x.weight for x in v.groups} for v in o.data.vertices],'faces':[list(f.vertices) for f in o.data.polygons],'materials':[o.data.materials[f.material_index].name for f in o.data.polygons],'keys':o.data.shape_keys is not None,'bones':len(rig.data.bones),'deform_bones':[b.name for b in rig.data.bones if b.use_deform]}
a=get('blender/ninola/working/01M3/2026-10-09-v006/ninola_01M3_concept_head_reconstruction.blend','01M3_Concept_Head_Reconstruction');b=get('blender/ninola/working/01M6/2026-10-09-v004/ninola_01M6_whole_cranial_blockout.blend','01M6_Whole_Cranial_Blockout');assert a['lock']==b['lock'];assert a['coords']==b['coords'][:len(a['coords'])];assert a['weights']==b['weights'][:len(a['weights'])];assert a['faces'][:5999]==b['faces'][:5999];assert a['materials'][:5999]==b['materials'][:5999]
ws=b['weights'][len(a['weights']):];err=max(abs(sum(w.values())-1) for w in ws);assert err<1e-6;assert all(set(w).issubset(b['deform_bones']) for w in ws)
report={'Rig_Trex_shape_keys_source_pose_signature_exact':True,'all_M3_source_rest_coords_and_weights_exact':True,'original_5999_retained_faces_and_materials_exact':True,'original_33_boundary_points_unmodified':True,'new_vertex_weights_sum_max_error':err,'new_vertex_weights_only_existing_deform_bones':True,'prototype_shape_keys':b['keys'],'bones':b['bones'],'M3_sha256':a['sha256'],'M6_sha256':b['sha256'],'production_integration':False};(p/'protection_verification.json').write_text(json.dumps(report,indent=2));print(json.dumps(report))
