import bpy,json,hashlib,math
from pathlib import Path
from mathutils import Matrix,Vector
r=Path.cwd();p=Path(__file__).resolve().parent;rec=json.loads((p/'build_record_v009.json').read_text());src=r/rec['source_path'];trial=r/rec['output_path'];ids=json.loads((p/'transfer_provenance_v009.json').read_text())['retained_original_vertex_ids'];changed={None};cams=json.loads((p.parent/'2026-10-09-review-v001/capture_settings.json').read_text());out=p/'pose-captures';out.mkdir(exist_ok=True)
def lock():
 rig=bpy.data.objects['TrexRig'];return {'bones':[(b.name,b.parent.name if b.parent else None,[list(row) for row in b.matrix_local]) for b in rig.data.bones],'pose':[(b.name,list(b.location),list(b.rotation_quaternion),list(b.rotation_euler),list(b.scale),b.rotation_mode) for b in rig.pose.bones],'keys':[(k.name,k.value,[list(v.co) for v in k.data]) for k in bpy.data.objects['Trex'].data.shape_keys.key_blocks]}
bpy.ops.wm.open_mainfile(filepath=str(src));a=bpy.data.objects['01Q1_Approved_Spine_Palette'];A=lock();coords=[list(v.co) for v in a.data.vertices];wt=[{a.vertex_groups[g.group].name:g.weight for g in v.groups} for v in a.data.vertices];bpy.ops.wm.open_mainfile(filepath=str(trial));o=bpy.data.objects[rec['object']];assert A==lock();assert len(ids)==len(o.data.vertices);assert all(list(v.co)==coords[ids[i]] for i,v in enumerate(o.data.vertices) if ids[i] not in changed);assert all({o.vertex_groups[g.group].name:g.weight for g in v.groups}==wt[ids[i]] for i,v in enumerate(o.data.vertices) if ids[i] is not None);checks=[]
for name,bone,angle,axis in [('jaw_open20','jaw',20,'X'),('jaw_open35','jaw',35,'X'),('head_turn10','head',10,'Z')]:
 bpy.ops.wm.open_mainfile(filepath=str(trial));o=bpy.data.objects[rec['object']];a=bpy.data.objects['01Q1_Approved_Spine_Palette'];rig=bpy.data.objects['TrexRig'];b=rig.pose.bones[bone];b.matrix_basis=b.matrix_basis@Matrix.Rotation(math.radians(angle),4,axis);bpy.context.view_layer.update();dep=bpy.context.evaluated_depsgraph_get();c=[o.matrix_world@v.co for v in o.evaluated_get(dep).data.vertices];aa=[a.matrix_world@v.co for v in a.evaluated_get(dep).data.vertices];delta=max((c[i]-aa[ids[i]]).length for i in range(len(c)) if ids[i] not in changed);assert delta<2e-6
 checks.append({'name':name,'bone':bone,'local_axis':axis,'angle_degrees':angle,'retained_vertex_evaluation_max_delta':delta,'scope':'artificial local test not full bite/locomotion/game'})
 sc=bpy.context.scene;sc.render.engine='BLENDER_WORKBENCH';sc.render.resolution_x=sc.render.resolution_y=1100;sc.render.resolution_percentage=100;sc.view_settings.view_transform='Standard';sc.display.shading.color_type='SINGLE';sc.display.shading.single_color=(.6,.64,.68);sc.display.shading.show_cavity=True;cd=bpy.data.cameras.new('R1PoseCam');cam=bpy.data.objects.new('R1PoseCam',cd);sc.collection.objects.link(cam);sc.camera=cam;cam.matrix_world=Matrix(cams['head_threequarter']['matrix']);cd.type='ORTHO';cd.ortho_scale=3.2
 for label,obj in [('source',a),('R1',o)]:
  for x in sc.objects:
   if x.type=='MESH':x.hide_render=x!=obj
  sc.render.filepath=str(out/f'{name}_{label}.png');bpy.ops.render.render(write_still=True)
assert hashlib.sha256(src.read_bytes()).hexdigest()==rec['source_sha256'];assert hashlib.sha256(trial.read_bytes()).hexdigest()==rec['sha256'];(p/'readback_pose_verification_v009.json').write_text(json.dumps({'Rig_names_hierarchy_rest_pose_channels_Trex_keys_exact':True,'unchanged_retained_bind_coordinates_exact':True,'all_retained_weights_exact':True,'new_donor_vertices':sum(i is None for i in ids),'retained_source_hashes_unchanged':True,'checks':checks,'full_deformation_export_game_acceptance':False},indent=2));print('R1 readback and three retained-vertex pose checks passed')
