import bpy,json,math,hashlib
from pathlib import Path
from mathutils import Vector
from mathutils.bvhtree import BVHTree
r=Path.cwd();p=Path(__file__).resolve().parent;src=r/'blender/ninola/working/01M4/2026-10-09-v001/ninola_01M4_cranial_identity.blend';before=hashlib.sha256(src.read_bytes()).hexdigest();bpy.ops.wm.open_mainfile(filepath=str(src));ob=bpy.data.objects['01M4_Cranial_Identity'];bpy.context.view_layer.update();me=ob.evaluated_get(bpy.context.evaluated_depsgraph_get()).data;c=[ob.matrix_world@v.co for v in me.vertices];names=[m.name for m in me.materials];skin=[f for f in me.polygons if names[f.material_index] in ['d_olive','d_tan','d_tan_lit','d_tan_dark']];bvh=BVHTree.FromPolygons(c,[list(f.vertices) for f in skin],all_triangles=False);eyes=[]
for sign in [-1,1]:
 fs=[f for f in me.polygons if names[f.material_index]=='Ninola_Iris_Gold_M4' and sum(c[i].x for i in f.vertices)*sign>0];ids=sorted({i for f in fs for i in f.vertices});center=sum((c[i] for i in ids),Vector())/len(ids);normal=sum(((c[f.vertices[1]]-c[f.vertices[0]]).cross(c[f.vertices[2]]-c[f.vertices[0]]) for f in fs),Vector()).normalized();eyes.append((sign,center,normal,ids))
headlen=max(v.y for v in c)-2.4;target=Vector((0,max(v.y for v in c)+5*headlen,sum(e[1].z for e in eyes)/2));helper=bpy.data.objects.new('Temporary_Common_Gaze_Target',None);bpy.context.scene.collection.objects.link(helper);helper.location=target
records=[]
for sign,center,n,ids in eyes:
 direction=(target-center).normalized();hit=bvh.ray_cast(center+direction*.0001,direction,(target-center).length);opening=[c[i] for i in range(len(c)) if i>=10561 and abs(c[i].y-2.98)<.12 and abs(c[i].z-2.435)<.09 and c[i].x*sign>0];records.append({'side':sign,'iris_surface_centroid_world':list(center),'iris_surface_normal_world':list(n),'iris_normal_angle_to_common_target_degrees':math.degrees(n.angle(direction)),'eye_sphere_center':None,'reason':'No independent sphere/eye object; current iris is surface patch, centroid is not eyeball center','skin_ray_hit':None if hit[0] is None else {'point':list(hit[0]),'distance':hit[3],'evaluated_face':skin[hit[2]].index},'iris_yz_extent':[max(c[i].y for i in ids)-min(c[i].y for i in ids),max(c[i].z for i in ids)-min(c[i].z for i in ids)]})
d={'source':str(src.relative_to(r)),'source_sha256':before,'object':ob.name,'world_forward_axis':'+Y','common_target_world':list(target),'target_role':'distant front diagnostic only; not production constraint or gaze prescription','eyes':records,'materials':names,'eye_objects':[o.name for o in bpy.data.objects if 'eye' in o.name.lower()],'limitations':['surface normal is geometric proxy, not biological optical axis','single neutral pose straight ray sample; no full visual field validation','naris location not inferred solely from absence of named material'],'saved_source':False};assert hashlib.sha256(src.read_bytes()).hexdigest()==before;(p/'gaze_diagnostic.json').write_text(json.dumps(d,indent=2));print(json.dumps({'target':list(target),'eyes':records},indent=2))
